In [25]:
import os
import gymnasium as gym
from stable_baselines3 import DQN
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize
from next_best_action_env.env import NextBestActionEnv

In [26]:
env = gym.make('NextBestActionEnv-v0')

In [21]:
state, _ = env.reset()

In [22]:
state

array([ 0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 10.,  2.,  3.,
        9.,  5.,  9.,  0., 10.,  7.,  1.,  9.,  7.,  6.,  4., 10.,  1.,
        3.,  4.,  7.,  3.,  2., -1., -1.], dtype=float32)

In [23]:
print(state[2:12])
print(state[23:33])
print("=====")
print(state[12:22])
print(state[33:43])
print("=====")
print(state[22])
print(state[43])

[1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
[10.  2.  3.  9.  5.  9.  0. 10.  7.  1.]
=====
[0. 0. 1. 1. 0. 0. 0. 0. 1. 0.]
[ 9.  7.  6.  4. 10.  1.  3.  4.  7.  3.]
=====
0.0
2.0


In [28]:
(10-10)/(10-0)

0.0

In [27]:
for i in range(0,21):
    print(env.unwrapped.get_reward(state, action=i))

(-10.0, False, {'action': 'Registration', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Payment', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Get Triage Number', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Measure Vital Signs', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'General Medicine Examination', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Eye Examination', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'ENT Examination', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Dental Examination', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Gynecological Examination', 'violation': 'must_not_do'})
(-10.0, False, {'action': 'Breast Examination', 'violation': 'repeat_action'})
(np.float64(5.5000000225), True, {'action': 'Blood Test'})
(np.float64(6.500000017500001), True, {'action': 'Urine Test'})
(-10.0, False, {'action': 'In-depth Eye Examination', 'violation': 'repeat_action'})
(-10.0, Fa

In [15]:
state, _ = env.reset()

In [16]:
state

array([ 1.      ,  0.      ,  1.      ,  1.      ,  1.      ,  1.      ,
        1.      ,  1.      ,  1.      ,  1.      ,  0.      ,  0.      ,
        1.      ,  1.      ,  0.      ,  0.      ,  0.      ,  0.      ,
        0.      ,  0.      ,  1.      ,  1.      ,  0.      ,  1.      ,
        3.      ,  8.      ,  8.      , 10.      ,  7.      ,  2.      ,
        6.      ,  9.      ,  5.      ,  2.      ,  4.      ,  4.      ,
        7.      ,  8.      ,  1.      ,  0.      ,  9.      ,  2.      ,
        5.      , 10.      , 77.61494 , 21.379429], dtype=float32)

In [17]:
print(state[2:12])
print(state[23:33])
print("=====")
print(state[12:22])
print(state[33:43])
print("=====")
print(state[22])
print(state[43])

[1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
[ 1.  3.  8.  8. 10.  7.  2.  6.  9.  5.]
=====
[1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
[2. 4. 4. 7. 8. 1. 0. 9. 2. 5.]
=====
0.0
10.0


In [18]:
for i in range(0,21):
    print(env.unwrapped.get_reward(state, action=i))

(-10.0, False, {'action': 'Registration', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Payment', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Get Triage Number', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Measure Vital Signs', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'General Medicine Examination', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Eye Examination', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'ENT Examination', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Dental Examination', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Gynecological Examination', 'violation': 'must_not_do'})
(-10.0, False, {'action': 'Breast Examination', 'violation': 'must_not_do'})
(-10.0, False, {'action': 'Blood Test', 'violation': 'repeat_action'})
(-10.0, False, {'action': 'Urine Test', 'violation': 'repeat_action'})
(np.float64(5.555555572016461), True, {'action': 'In-depth Eye Examination'})
